image: node:20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  script:
    - npm install
    - npm run build
    - mkdir artifacts/
    - cd build/
    - npm pack --pack-destination='../artifacts'
  artifacts:
    paths:
      - build/artifacts
    expire_in: 1 week
    untracked: true
