image: node:20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build:
  script:
    - npm install
    - npm run build
    - cd build/
    - npm pack
  artifacts:
    paths:
      - build/
    expire_in: 1 week
    untracked: true
