image: node:20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/


stages:
  - build
  - release

build-job:
  stage: build
  script:
    - echo BUILD_JOB_ID=$CI_JOB_ID >> CI_JOB_ID.env
    - export PACKAGE_VERSION=$(npm pkg get version --workspaces=false | tr -d \")
    - npm install
    - npm run build
    - mkdir artifacts/
    - cd build/
    - npm pack --pack-destination='../artifacts'
    - cd ../artifacts
    - mv website-evidence-collector-$PACKAGE_VERSION.tgz website-evidence-collector.tgz
  artifacts:
    paths:
      - build/artifacts
    reports:
      dotenv: CI_JOB_ID.env
    expire_in: never
    untracked: true

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: build-job
      artifacts: true
  script:
    - echo "Release application..."
  release:
    name: 'Release Executables $CI_COMMIT_TAG'
    description: 'Created using the release-cli'
    tag_name: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'Website Evidence Collector $CI_COMMIT_TAG'
          # Use variables to build a URL to access the artifacts
          # ${CI_PROJECT_URL} is the repository URL
          # ${BUILD_JOB_ID} is from the previous job,
          # the build stage, that contains the artifact
          url: '${CI_PROJECT_URL}/-/jobs/${BUILD_JOB_ID}/artifacts/file/build/website-evidence-collector.tgz'
