#podman build -t custom-tinyproxy -f Containerfile
# podman run -it --rm --name='tinyproxy' -e UPSTREAM_PROXY_CONFIG="felix:somepassword@localhost:8080"  --pod=proxy-env  localhost/custom-tinyproxy:latest

FROM alpine:3.20.0

RUN apk add --no-cache tinyproxy envsubst

WORKDIR /root/

COPY ./tinyproxy.conf tinyproxy.conf

EXPOSE 8888

CMD envsubst < tinyproxy.conf | tinyproxy -d -c /proc/self/fd/0
